server:
  port: 80
spring:
  datasource:
    url: jdbc:mysql:///jtsys?serverTimezone=GMT%2B8&characterEncoding=utf8
    username: root
    password: root
  thymeleaf:
    prefix: classpath:/templates/pages/
  aop:
    proxy-target-class: true
  #true是默认的CGLIB子类继承代理,false是JDK兄弟代理
mybatis:
  mapper-locations:
    - classpath:/mapper/*.xml
logging:
  level:
    com.cy: debug